enum ClaudeConfigNames {
    static let hooksKey = "hooks"
    static let permissionsKey = "permissions"
    static let allowKey = "allow"
    static let denyKey = "deny"
    static let enabledPluginsKey = "enabledPlugins"
    static let extraKnownMarketplacesKey = "extraKnownMarketplaces"
    static let pluginMarketplacesKey = "pluginMarketplaces"
    static let pluginsKey = "plugins"
    static let sourceKey = "source"
    static let nameKey = "name"
    static let pathKey = "path"
    static let settingsOrigin = "claude-settings"
    static let customizationOrigin = "claude-customization"
    static let pluginOrigin = "claude-plugin"
    static let hookOrigin = "claude-hook"
    static let instructionOrigin = "claude-instruction"
    static let permissionAllowName = "permissions.allow"
    static let permissionDenyName = "permissions.deny"
    static let pluginsDirectoryComponent = "plugins"
    static let knownMarketplacesName = "known-marketplaces.json"
    static let installedPluginsName = "installed-plugins.json"
    static let managedSettingsPath = "/Library/Application Support/ClaudeCode/managed-settings.json"
}
